name: AriKeys
version: '${project.version}'
main: org.alvindimas05.arikeys.AriKeysPlugin
api-version: 1.21
author: alvindimas05
description: AriKeys Plugin lets your server receive keybind presses from the AriKeys client.
softdepend: [ PlaceholderAPI, MythicMobs ]
commands:
  arikeys:
    description: The main command for AriKeys.
    aliases: [ "ak", "keys" ]
    permission: arikeys.admin
    usage: "Usage: /arikeys [reload|info]"
permissions:
  arikeys.admin:
    description: The main permission for AriKeys.
    default: op