name: Publish Jar
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release git tag
        type: string
        required: true
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: mythiccontrols
          settings-path: ${{ github.workspace }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "9.0"
      - name: Build Mods with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-jar
          path: ./fabric/build/libs/*
      - name: Publish release
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./fabric/build/libs/mythiccontrols-fabric-${{ inputs.tag }}.jar
          tag: ${{ inputs.tag }}
          name: MythicControls ${{ inputs.tag }}
          allowUpdates: true
          artifactErrorsFailBuild: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}