name: Publish Jar
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release git tag
        type: string
        required: true
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: arikeys
          settings-path: ${{ github.workspace }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
      - uses: SpraxDev/Action-SpigotMC@v5
        with:
          versions: 1.21
      - name: Build Plugin with Maven
        working-directory: ./arikeys-plugin
        run: mvn package
      - name: Build Mods with Gradle
        working-directory: ./arikeys-mod
        run: |
          chmod +x ./gradlew
          ./gradlew build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-jar
          path: ./arikeys-plugin/target/*.jar,./arikeys-mod/fabric/build/libs/arikeys-mod-fabric-2.4.jar,./arikeys-mod/neoforge/build/libs/arikeys-mod-neoforge-2.4.jar
      - name: Publish release
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: ./arikeys-plugin/target/*.jar,./arikeys-mod/fabric/build/libs/arikeys-mod-fabric-2.4.jar,./arikeys-mod/neoforge/build/libs/arikeys-mod-neoforge-2.4.jar
          tag: ${{ inputs.tag }}
          name: LagAssist ${{ inputs.tag }}
          allowUpdates: true
          artifactErrorsFailBuild: false
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}